### ISSUE TITLE
Readme discord server image does not link to the server

### ISSUE THREAD

**Issue by Cerberus1746** [MilkJug1/OculusLinkLinux#24]
**Describe the bug**
The Discord server button in the readme just opens the image, it is not linked to the server invite.

**To Reproduce**
1. Click the discord server image.
2. Get a "bigger" image in a new tab 

**Expected behavior**
Entrance to the discord server

**Screenshots**
![image](https://user-images.githubusercontent.com/291051/207957727-08e1c8ea-c022-4f38-bbeb-bda6cec75213.png)

**Desktop (please complete the following information):**
Ok, you got the idea :-P

**Comment by MilkJug1** [comment]
Oh, thanks for bringing to my attention! This was working a while ago, for some reason its not now. I don't know what caused it but a fix should be coming up here shortly

**Comment by Cerberus1746** [comment]
just add the link on the page by this point xD

**Comment by MilkJug1** [comment]
I may have to now, not sure why discord is doing this. Random change with discord breaking Readme, unfortunately.
