### ISSUE TITLE
Error USBConnection.cc when trying to make 

### ISSUE THREAD

**Issue by dozadoesit** [MilkJug1/OculusLinkLinux#26]
When trying to make I get the following error:

src//TrackingControl.cc:6:1: warning: no return statement in function returning non-void [-Wreturn-type]
    6 | }
      | ^
src//USBConnection.cc:7:29: error: expected ‘,’ or ‘...’ before ‘*’ token
    7 | int main(int argc, char argv*)
      |                             ^
src//USBConnection.cc:7:5: warning: second argument of ‘int main(int, char)’ should be ‘char **’ [-Wmain]
    7 | int main(int argc, char argv*)
      |     ^~~~
make: *** [<builtin>: src//USBConnection.o] Error 1

I fixed this by doing the following:

Change main function to the following: int main(int argc, char* argv[])

**Comment by MilkJug1** [comment]
Fixed in commit #28 so this build issue wouldn't happen on main branch now.
